
package vista;
import java.sql.Connection;//conexion a BD
import java.sql.DriverManager;//driver de conexion
import java.sql.ResultSet;//resultado final de datos
import java.sql.ResultSetMetaData;//resultado de metadatos
import java.sql.SQLException;//Tratamiento de Errros de BD SQL
import java.sql.Statement;//Generador de sentencias SQL
import java.text.SimpleDateFormat;//Formatear datos
import java.util.Date;//fecha de sistema
import javax.swing.ImageIcon;//Tratamiento de imagenes
import javax.swing.JOptionPane;//ventanas emergentes
import javax.swing.table.DefaultTableModel;//tabla de datos
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.view.JasperViewer;

import pojos.Predio;

public class Aplicacion extends javax.swing.JFrame {

    
    //clases de conexion y sus objetos

    public Connection cn;
    public Statement stmt;
    public ResultSet rs;//punto final para tratamiento de los datos
    Predio objetoPredio = new Predio();//OBJETO predio

   
    public Aplicacion() {
        initComponents();
    }
    //metodo para conectar a bd
    public void conectarBase() {
        try { //inicia try
            Class.forName("com.mysql.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost/bdtramite", "adminedith", "edith123");
            JOptionPane.showMessageDialog(null, "Conexion a BD OK\n\nTRAMITE CIUDADANO");
            stmt = cn.createStatement();//genera sentencias sobre objetos de base de datos
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error de base de datos 1: \n" + ex);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error de base de datos 2:" + e);
        }
    }//termina metodo conectar
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPrincipal = new javax.swing.JPanel();
        jpAltaPredio = new javax.swing.JPanel();
        btnAgregarPredio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txfClave = new javax.swing.JTextField();
        txfSuperficie = new javax.swing.JTextField();
        txfValor = new javax.swing.JTextField();
        txfUbicacion = new javax.swing.JTextField();
        txfAnio = new javax.swing.JTextField();
        txfTotal = new javax.swing.JTextField();
        jpEditarPredio = new javax.swing.JPanel();
        btnEditarPredio = new javax.swing.JButton();
        btnBuscarPredio = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txfValorEditar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txfSuperficieEditar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txfTotalEditar = new javax.swing.JTextField();
        txfUbicacionEditar = new javax.swing.JTextField();
        txfClaveEditar = new javax.swing.JTextField();
        txfAnioEditar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jpActualizarCarpeta = new javax.swing.JPanel();
        btnActualizarPredio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtConsultaPredios = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jpEliminarPredio = new javax.swing.JPanel();
        btnEliminarPredio = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txfClaveEliminar = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmiPDF = new javax.swing.JMenuItem();
        jmiImprimir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SERVICIOS ADMINISTRATIVOS");
        setPreferredSize(new java.awt.Dimension(918, 1000));

        jpPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jpAltaPredio.setBackground(new java.awt.Color(0, 102, 0));
        jpAltaPredio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Alta Predio.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        btnAgregarPredio.setText("AGREGAR");
        btnAgregarPredio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPredioActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Clave:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Superficie:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ubicación:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Año:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total:");

        javax.swing.GroupLayout jpAltaPredioLayout = new javax.swing.GroupLayout(jpAltaPredio);
        jpAltaPredio.setLayout(jpAltaPredioLayout);
        jpAltaPredioLayout.setHorizontalGroup(
            jpAltaPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAltaPredioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAltaPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpAltaPredioLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txfClave, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAltaPredioLayout.createSequentialGroup()
                        .addGroup(jpAltaPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addGroup(jpAltaPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfSuperficie)
                            .addComponent(txfValor)
                            .addComponent(txfUbicacion)
                            .addComponent(txfAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(97, 97, 97))
            .addGroup(jpAltaPredioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnAgregarPredio, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpAltaPredioLayout.setVerticalGroup(
            jpAltaPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAltaPredioLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jpAltaPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txfClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpAltaPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txfSuperficie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAltaPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpAltaPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txfUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAltaPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txfAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpAltaPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregarPredio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpEditarPredio.setBackground(new java.awt.Color(0, 102, 0));
        jpEditarPredio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar Predio.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        btnEditarPredio.setText("EDITAR");
        btnEditarPredio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPredioActionPerformed(evt);
            }
        });

        btnBuscarPredio.setText("BUSCAR");
        btnBuscarPredio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPredioActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Superficie:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Clave:");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ubicación:");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Año:");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total:");

        txfClaveEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfClaveEditarActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Valor:");

        javax.swing.GroupLayout jpEditarPredioLayout = new javax.swing.GroupLayout(jpEditarPredio);
        jpEditarPredio.setLayout(jpEditarPredioLayout);
        jpEditarPredioLayout.setHorizontalGroup(
            jpEditarPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditarPredioLayout.createSequentialGroup()
                .addGroup(jpEditarPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEditarPredioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpEditarPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEditarPredioLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txfClaveEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEditarPredioLayout.createSequentialGroup()
                                .addGroup(jpEditarPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(jpEditarPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txfSuperficieEditar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                    .addComponent(txfValorEditar)
                                    .addComponent(txfUbicacionEditar)
                                    .addComponent(txfAnioEditar)
                                    .addComponent(txfTotalEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jpEditarPredioLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnBuscarPredio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarPredio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpEditarPredioLayout.setVerticalGroup(
            jpEditarPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditarPredioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEditarPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txfClaveEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpEditarPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txfSuperficieEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEditarPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txfValorEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpEditarPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txfUbicacionEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEditarPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txfAnioEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpEditarPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txfTotalEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jpEditarPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarPredio)
                    .addComponent(btnEditarPredio))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jpActualizarCarpeta.setBackground(new java.awt.Color(0, 102, 0));
        jpActualizarCarpeta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carpeta Ciudadana.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        btnActualizarPredio.setText("ACTUALIZAR");
        btnActualizarPredio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarPredioActionPerformed(evt);
            }
        });

        jtConsultaPredios.setBackground(new java.awt.Color(0, 102, 0));
        jtConsultaPredios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jtConsultaPredios.setForeground(new java.awt.Color(255, 255, 255));
        jtConsultaPredios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Predio", "Clave", "Superficie", "Valor", "Ubicacion", "Año", "Total"
            }
        ));
        jScrollPane1.setViewportView(jtConsultaPredios);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Untitled design (4).png"))); // NOI18N

        javax.swing.GroupLayout jpActualizarCarpetaLayout = new javax.swing.GroupLayout(jpActualizarCarpeta);
        jpActualizarCarpeta.setLayout(jpActualizarCarpetaLayout);
        jpActualizarCarpetaLayout.setHorizontalGroup(
            jpActualizarCarpetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpActualizarCarpetaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpActualizarCarpetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpActualizarCarpetaLayout.createSequentialGroup()
                        .addComponent(btnActualizarPredio)
                        .addGap(407, 407, 407))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpActualizarCarpetaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))))
        );
        jpActualizarCarpetaLayout.setVerticalGroup(
            jpActualizarCarpetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpActualizarCarpetaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizarPredio)
                .addGap(13, 13, 13)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpEliminarPredio.setBackground(new java.awt.Color(0, 102, 0));
        jpEliminarPredio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eliminar Predio.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        btnEliminarPredio.setText("ELIMINAR");
        btnEliminarPredio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPredioActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Clave Predial:");

        txfClaveEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfClaveEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpEliminarPredioLayout = new javax.swing.GroupLayout(jpEliminarPredio);
        jpEliminarPredio.setLayout(jpEliminarPredioLayout);
        jpEliminarPredioLayout.setHorizontalGroup(
            jpEliminarPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEliminarPredioLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jpEliminarPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEliminarPredioLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEliminarPredioLayout.createSequentialGroup()
                        .addGroup(jpEliminarPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEliminarPredio, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfClaveEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))))
        );
        jpEliminarPredioLayout.setVerticalGroup(
            jpEliminarPredioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEliminarPredioLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(txfClaveEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminarPredio)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpPrincipalLayout = new javax.swing.GroupLayout(jpPrincipal);
        jpPrincipal.setLayout(jpPrincipalLayout);
        jpPrincipalLayout.setHorizontalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addComponent(jpAltaPredio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpEditarPredio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpEliminarPredio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addComponent(jpActualizarCarpeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpPrincipalLayout.setVerticalGroup(
            jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPrincipalLayout.createSequentialGroup()
                .addComponent(jpActualizarCarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpEditarPredio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpAltaPredio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpEliminarPredio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(288, Short.MAX_VALUE))
        );

        jpActualizarCarpeta.getAccessibleContext().setAccessibleName("Actualizar Predio");

        jMenu2.setText("Reporte");

        jmiPDF.setText("PDF");
        jmiPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPDFActionPerformed(evt);
            }
        });
        jMenu2.add(jmiPDF);

        jmiImprimir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jmiImprimir.setText("Imprimir");
        jmiImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiImprimirActionPerformed(evt);
            }
        });
        jMenu2.add(jmiImprimir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPredioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPredioActionPerformed
        //Llamada a metodo conectar
        conectarBase();

        String altaLibro = "";//almacena lo valores capturados y anviarlos a bd
        //almacenar valores desde formulario:
        objetoPredio.setClave(Float.parseFloat(txfClave.getText()));
        objetoPredio.setSuperficie(Float.parseFloat(txfSuperficie.getText()));
        objetoPredio.setValor(Double.parseDouble(txfValor.getText()));
        objetoPredio.setUbucacion(txfUbicacion.getText());
        objetoPredio.setAnio(Float.parseFloat(txfAnio.getText()));
        objetoPredio.setTotal(Double.parseDouble(txfTotal.getText()));

        altaLibro = "INSERT INTO tpredio (`clave`,`superficie`,`valor`,`ubicacion`,`anio`,`total`) VALUES ('" + objetoPredio.getClave()+ "','" + objetoPredio.getSuperficie()+ "','" 
                + objetoPredio.getValor()+ "','" + objetoPredio.getUbucacion()+ "','" + objetoPredio.getAnio()+ "','" +objetoPredio.getTotal()+ "')";//
        try {
            stmt.executeUpdate(altaLibro);
            JOptionPane.showMessageDialog(null, "Se registro predio exitosamente\n " + objetoPredio.getClave());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error bd al generar alta\n Verifica: " + e);
        }
        
    }//GEN-LAST:event_btnAgregarPredioActionPerformed

    private void btnBuscarPredioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPredioActionPerformed
         try {
            conectarBase();
            objetoPredio.setClave(Float.parseFloat(txfClaveEditar.getText()));
            rs=stmt.executeQuery("SELECT * from tpredio where clave = '"+objetoPredio.getClave()+"'");
            JOptionPane.showMessageDialog(null,"Buscando el Predio... ");
            if (rs.next()==true) {
                //imprimir datos del libro encontrado
                this.txfSuperficieEditar.setText(rs.getString("superficie"));
                this.txfValorEditar.setText(rs.getString("valor"));
                this.txfUbicacionEditar.setText(rs.getString("ubicacion"));
                this.txfAnioEditar.setText(rs.getString("anio"));
                this.txfTotalEditar.setText(rs.getString("total"));
            } else {
                JOptionPane.showMessageDialog(null,"Error no exite el predio, valida que la clave sea correcta.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Error de BD busqueda"+ e);
        }
    }//GEN-LAST:event_btnBuscarPredioActionPerformed

    private void txfClaveEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfClaveEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfClaveEditarActionPerformed

    private void btnEditarPredioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPredioActionPerformed
         String actualizarPredio="";
        try {
            conectarBase();
            objetoPredio.setSuperficie(Float.parseFloat(txfSuperficieEditar.getText()));
            objetoPredio.setValor(Double.parseDouble(txfValorEditar.getText()));
            objetoPredio.setUbucacion(txfUbicacionEditar.getText());
            objetoPredio.setAnio(Float.parseFloat(txfAnioEditar.getText()));
            objetoPredio.setTotal(Double.parseDouble(txfTotalEditar.getText()));
            
            actualizarPredio="UPDATE tpredio SET superficie= '"+objetoPredio.getSuperficie()+"', valor = '"+objetoPredio.getValor()+"', ubicacion = '"+objetoPredio.getUbucacion()+"', anio = '"+objetoPredio.getAnio()+"', total = '"+objetoPredio.getTotal()+"' WHERE clave= '"+objetoPredio.getClave()+"'";
            stmt.executeUpdate(actualizarPredio);
            JOptionPane.showMessageDialog(null, "Datos del Predio actualizado\nValida tu consulta");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "error de bd"+e);
        }
    }//GEN-LAST:event_btnEditarPredioActionPerformed

    private void btnActualizarPredioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarPredioActionPerformed
        try {
            conectarBase();
            //Objeto almacenamiento logico de datos, modelo de datos
            DefaultTableModel modeloDatos = new DefaultTableModel();
            jtConsultaPredios.setModel(modeloDatos);
            rs = stmt.executeQuery("select * from tpredio");

            ResultSetMetaData rsmd = rs.getMetaData();
            int cantidadColumnas = rsmd.getColumnCount();
            //titulos de las col:

            modeloDatos.addColumn("Id Predio");
            modeloDatos.addColumn("Clave");
            modeloDatos.addColumn("Superficie");
            modeloDatos.addColumn("Valor");
            modeloDatos.addColumn("Ubicacion");
            modeloDatos.addColumn("Año");
            modeloDatos.addColumn("Total");
            //imprimir registros
            while (rs.next()) {
                Object fila[] = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    fila[i] = rs.getObject(i + 1);
                }//termina for
                modeloDatos.addRow(fila);
            }//termina while

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error bd consulta" + ex);
        }
    }//GEN-LAST:event_btnActualizarPredioActionPerformed

    private void btnEliminarPredioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPredioActionPerformed
        int confirmaBaja;
        
        try {
            conectarBase();
            
            String predioBaja=txfClaveEliminar.getText();
            confirmaBaja=stmt.executeUpdate("DELETE FROM tpredio where clave= '"+predioBaja+"' ");
            if (confirmaBaja==1) {
                JOptionPane.showMessageDialog(null,"Se dio de baja el predio de la BD\n\n:"+confirmaBaja);
                
            } else {
                JOptionPane.showMessageDialog(null,"Error, no existe la Clave Predial en la BD\n\n:");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Error de BD baja"+ e);
        }
    }//GEN-LAST:event_btnEliminarPredioActionPerformed

    private void txfClaveEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfClaveEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfClaveEliminarActionPerformed

    private void jmiPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPDFActionPerformed
        conectarBase();
        try {
            String rutaReporte="src/reportes/rcarpeta.jasper";
            JasperPrint rptlibrosPDF = JasperFillManager.fillReport(rutaReporte,null,cn);
            JasperViewer ventanaVisor = new JasperViewer(rptlibrosPDF,false);
            ventanaVisor.setTitle("Carpeta Ciudadana.");
            ventanaVisor.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error en informe Verifica\n\n"+ e);
        }
    }//GEN-LAST:event_jmiPDFActionPerformed

    private void jmiImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiImprimirActionPerformed
        conectarBase();
        try {
            String rutaRepote="src/reportes/rcarpeta.jasper";
            JasperPrint rptlibrosPDF=JasperFillManager.fillReport(rutaRepote, null,cn);
            JasperPrintManager.printReport(rptlibrosPDF, true);
            JOptionPane.showMessageDialog(null, "Enviando reporte a impresora HP DeskJet");
            
                    
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error bd en informe Verifica\n\n"+e);
        }
    }//GEN-LAST:event_jmiImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarPredio;
    private javax.swing.JButton btnAgregarPredio;
    private javax.swing.JButton btnBuscarPredio;
    private javax.swing.JButton btnEditarPredio;
    private javax.swing.JButton btnEliminarPredio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jmiImprimir;
    private javax.swing.JMenuItem jmiPDF;
    private javax.swing.JPanel jpActualizarCarpeta;
    private javax.swing.JPanel jpAltaPredio;
    private javax.swing.JPanel jpEditarPredio;
    private javax.swing.JPanel jpEliminarPredio;
    private javax.swing.JPanel jpPrincipal;
    private javax.swing.JTable jtConsultaPredios;
    private javax.swing.JTextField txfAnio;
    private javax.swing.JTextField txfAnioEditar;
    private javax.swing.JTextField txfClave;
    private javax.swing.JTextField txfClaveEditar;
    private javax.swing.JTextField txfClaveEliminar;
    private javax.swing.JTextField txfSuperficie;
    private javax.swing.JTextField txfSuperficieEditar;
    private javax.swing.JTextField txfTotal;
    private javax.swing.JTextField txfTotalEditar;
    private javax.swing.JTextField txfUbicacion;
    private javax.swing.JTextField txfUbicacionEditar;
    private javax.swing.JTextField txfValor;
    private javax.swing.JTextField txfValorEditar;
    // End of variables declaration//GEN-END:variables
}
